name: Deploy to AKS with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1
      with:
        azcliversion: 2.0.72

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CREDENTIALS }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Set AKS context
      run: az aks get-credentials --resource-group rg-ais-payment-gateway --name sbpocaks 

    - name: Deploy Nginx to AKS using Helm
      run: |
        helm upgrade --install nginx-release ./path/to/your/helm/chart \
          --namespace paint-sandbox \
          --values path/to/your/helm/chart/values.yaml
