name: Deploy to AKS

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI Login
      run: az login

    - name: Configure kubectl
      run: az aks get-credentials --resource-group rg-ais-payment-gateway --name sbpocaks

    - name: Deploy Nginx to AKS
      run: kubectl apply -f nginx-deployment.yaml  
